package Hibernate;
// Generated Jan 30, 2019 7:46:47 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Appointment generated by hbm2java
 */
public class Appointment  implements java.io.Serializable {


     private Integer id;
     private Jobs jobs;
     private User userByAdmin;
     private TimesHasUser timesHasUser;
     private User userByClient;
     private Date date;
     private String status;
     private String discription;

    public Appointment() {
    }

	
    public Appointment(Jobs jobs, User userByAdmin, TimesHasUser timesHasUser, User userByClient) {
        this.jobs = jobs;
        this.userByAdmin = userByAdmin;
        this.timesHasUser = timesHasUser;
        this.userByClient = userByClient;
    }
    public Appointment(Jobs jobs, User userByAdmin, TimesHasUser timesHasUser, User userByClient, Date date, String status, String discription) {
       this.jobs = jobs;
       this.userByAdmin = userByAdmin;
       this.timesHasUser = timesHasUser;
       this.userByClient = userByClient;
       this.date = date;
       this.status = status;
       this.discription = discription;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Jobs getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Jobs jobs) {
        this.jobs = jobs;
    }
    public User getUserByAdmin() {
        return this.userByAdmin;
    }
    
    public void setUserByAdmin(User userByAdmin) {
        this.userByAdmin = userByAdmin;
    }
    public TimesHasUser getTimesHasUser() {
        return this.timesHasUser;
    }
    
    public void setTimesHasUser(TimesHasUser timesHasUser) {
        this.timesHasUser = timesHasUser;
    }
    public User getUserByClient() {
        return this.userByClient;
    }
    
    public void setUserByClient(User userByClient) {
        this.userByClient = userByClient;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDiscription() {
        return this.discription;
    }
    
    public void setDiscription(String discription) {
        this.discription = discription;
    }




}


