package Hibernate;
// Generated Jan 30, 2019 7:46:47 AM by Hibernate Tools 3.6.0



/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private Integer idcontact;
     private User user;
     private String mobile;

    public Contact() {
    }

	
    public Contact(User user) {
        this.user = user;
    }
    public Contact(User user, String mobile) {
       this.user = user;
       this.mobile = mobile;
    }
   
    public Integer getIdcontact() {
        return this.idcontact;
    }
    
    public void setIdcontact(Integer idcontact) {
        this.idcontact = idcontact;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }




}


