package Hibernate;
// Generated Jan 30, 2019 7:46:47 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Dates generated by hbm2java
 */
public class Dates  implements java.io.Serializable {


     private Integer iddates;
     private String date;
     private Set<TimesHasUser> timesHasUsers = new HashSet<TimesHasUser>(0);

    public Dates() {
    }

    public Dates(String date, Set<TimesHasUser> timesHasUsers) {
       this.date = date;
       this.timesHasUsers = timesHasUsers;
    }
   
    public Integer getIddates() {
        return this.iddates;
    }
    
    public void setIddates(Integer iddates) {
        this.iddates = iddates;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Set<TimesHasUser> getTimesHasUsers() {
        return this.timesHasUsers;
    }
    
    public void setTimesHasUsers(Set<TimesHasUser> timesHasUsers) {
        this.timesHasUsers = timesHasUsers;
    }




}


