package Hibernate;
// Generated Jan 30, 2019 7:46:47 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Gender generated by hbm2java
 */
public class Gender  implements java.io.Serializable {


     private Integer idgender;
     private String gen;
     private Set<User> users = new HashSet<User>(0);
     private Set<Jobs> jobses = new HashSet<Jobs>(0);

    public Gender() {
    }

    public Gender(String gen, Set<User> users, Set<Jobs> jobses) {
       this.gen = gen;
       this.users = users;
       this.jobses = jobses;
    }
   
    public Integer getIdgender() {
        return this.idgender;
    }
    
    public void setIdgender(Integer idgender) {
        this.idgender = idgender;
    }
    public String getGen() {
        return this.gen;
    }
    
    public void setGen(String gen) {
        this.gen = gen;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }
    public Set<Jobs> getJobses() {
        return this.jobses;
    }
    
    public void setJobses(Set<Jobs> jobses) {
        this.jobses = jobses;
    }




}


