package Hibernate;
// Generated Jan 30, 2019 7:46:47 AM by Hibernate Tools 3.6.0



/**
 * JobsHasQualification generated by hbm2java
 */
public class JobsHasQualification  implements java.io.Serializable {


     private Integer id;
     private Qualification qualification;
     private Jobs jobs;

    public JobsHasQualification() {
    }

    public JobsHasQualification(Qualification qualification, Jobs jobs) {
       this.qualification = qualification;
       this.jobs = jobs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Qualification getQualification() {
        return this.qualification;
    }
    
    public void setQualification(Qualification qualification) {
        this.qualification = qualification;
    }
    public Jobs getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Jobs jobs) {
        this.jobs = jobs;
    }




}


