package Hibernate;
// Generated Jan 30, 2019 7:46:47 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Jobs generated by hbm2java
 */
public class Jobs  implements java.io.Serializable {


     private Integer idjobs;
     private Country country;
     private Gender gender;
     private String name;
     private String status;
     private String des;
     private Double salary;
     private Set<JobsHasQualification> jobsHasQualifications = new HashSet<JobsHasQualification>(0);
     private Set<Appointment> appointments = new HashSet<Appointment>(0);

    public Jobs() {
    }

	
    public Jobs(Country country, Gender gender) {
        this.country = country;
        this.gender = gender;
    }
    public Jobs(Country country, Gender gender, String name, String status, String des, Double salary, Set<JobsHasQualification> jobsHasQualifications, Set<Appointment> appointments) {
       this.country = country;
       this.gender = gender;
       this.name = name;
       this.status = status;
       this.des = des;
       this.salary = salary;
       this.jobsHasQualifications = jobsHasQualifications;
       this.appointments = appointments;
    }
   
    public Integer getIdjobs() {
        return this.idjobs;
    }
    
    public void setIdjobs(Integer idjobs) {
        this.idjobs = idjobs;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public Gender getGender() {
        return this.gender;
    }
    
    public void setGender(Gender gender) {
        this.gender = gender;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    public Double getSalary() {
        return this.salary;
    }
    
    public void setSalary(Double salary) {
        this.salary = salary;
    }
    public Set<JobsHasQualification> getJobsHasQualifications() {
        return this.jobsHasQualifications;
    }
    
    public void setJobsHasQualifications(Set<JobsHasQualification> jobsHasQualifications) {
        this.jobsHasQualifications = jobsHasQualifications;
    }
    public Set<Appointment> getAppointments() {
        return this.appointments;
    }
    
    public void setAppointments(Set<Appointment> appointments) {
        this.appointments = appointments;
    }




}


