package Hibernate;
// Generated Jan 30, 2019 7:46:47 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Qualification generated by hbm2java
 */
public class Qualification  implements java.io.Serializable {


     private Integer qliid;
     private String qulification;
     private String value;
     private Set<JobsHasQualification> jobsHasQualifications = new HashSet<JobsHasQualification>(0);

    public Qualification() {
    }

    public Qualification(String qulification, String value, Set<JobsHasQualification> jobsHasQualifications) {
       this.qulification = qulification;
       this.value = value;
       this.jobsHasQualifications = jobsHasQualifications;
    }
   
    public Integer getQliid() {
        return this.qliid;
    }
    
    public void setQliid(Integer qliid) {
        this.qliid = qliid;
    }
    public String getQulification() {
        return this.qulification;
    }
    
    public void setQulification(String qulification) {
        this.qulification = qulification;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set<JobsHasQualification> getJobsHasQualifications() {
        return this.jobsHasQualifications;
    }
    
    public void setJobsHasQualifications(Set<JobsHasQualification> jobsHasQualifications) {
        this.jobsHasQualifications = jobsHasQualifications;
    }




}


