package Hibernate;
// Generated Jan 30, 2019 7:46:47 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Times generated by hbm2java
 */
public class Times  implements java.io.Serializable {


     private Integer idtimes;
     private String time;
     private Set<TimesHasUser> timesHasUsers = new HashSet<TimesHasUser>(0);

    public Times() {
    }

    public Times(String time, Set<TimesHasUser> timesHasUsers) {
       this.time = time;
       this.timesHasUsers = timesHasUsers;
    }
   
    public Integer getIdtimes() {
        return this.idtimes;
    }
    
    public void setIdtimes(Integer idtimes) {
        this.idtimes = idtimes;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public Set<TimesHasUser> getTimesHasUsers() {
        return this.timesHasUsers;
    }
    
    public void setTimesHasUsers(Set<TimesHasUser> timesHasUsers) {
        this.timesHasUsers = timesHasUsers;
    }




}


