package Hibernate;
// Generated Jan 30, 2019 7:46:47 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TimesHasUser generated by hbm2java
 */
public class TimesHasUser  implements java.io.Serializable {


     private Integer id;
     private Dates dates;
     private Times times;
     private User user;
     private Set<Appointment> appointments = new HashSet<Appointment>(0);

    public TimesHasUser() {
    }

	
    public TimesHasUser(Dates dates, Times times, User user) {
        this.dates = dates;
        this.times = times;
        this.user = user;
    }
    public TimesHasUser(Dates dates, Times times, User user, Set<Appointment> appointments) {
       this.dates = dates;
       this.times = times;
       this.user = user;
       this.appointments = appointments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Dates getDates() {
        return this.dates;
    }
    
    public void setDates(Dates dates) {
        this.dates = dates;
    }
    public Times getTimes() {
        return this.times;
    }
    
    public void setTimes(Times times) {
        this.times = times;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set<Appointment> getAppointments() {
        return this.appointments;
    }
    
    public void setAppointments(Set<Appointment> appointments) {
        this.appointments = appointments;
    }




}


