package Hibernate;
// Generated Jan 30, 2019 7:46:47 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer uid;
     private Gender gender;
     private Type type;
     private String fname;
     private String lname;
     private String status;
     private String email;
     private String password;
     private Set<Appointment> appointmentsForClient = new HashSet<Appointment>(0);
     private Set<Appointment> appointmentsForAdmin = new HashSet<Appointment>(0);
     private Set<Contact> contacts = new HashSet<Contact>(0);
     private Set<TimesHasUser> timesHasUsers = new HashSet<TimesHasUser>(0);
     private Set<Address> addresses = new HashSet<Address>(0);
     private Set<Usercountry> usercountries = new HashSet<Usercountry>(0);

    public User() {
    }

	
    public User(Gender gender, Type type) {
        this.gender = gender;
        this.type = type;
    }
    public User(Gender gender, Type type, String fname, String lname, String status, String email, String password, Set<Appointment> appointmentsForClient, Set<Appointment> appointmentsForAdmin, Set<Contact> contacts, Set<TimesHasUser> timesHasUsers, Set<Address> addresses, Set<Usercountry> usercountries) {
       this.gender = gender;
       this.type = type;
       this.fname = fname;
       this.lname = lname;
       this.status = status;
       this.email = email;
       this.password = password;
       this.appointmentsForClient = appointmentsForClient;
       this.appointmentsForAdmin = appointmentsForAdmin;
       this.contacts = contacts;
       this.timesHasUsers = timesHasUsers;
       this.addresses = addresses;
       this.usercountries = usercountries;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public Gender getGender() {
        return this.gender;
    }
    
    public void setGender(Gender gender) {
        this.gender = gender;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Appointment> getAppointmentsForClient() {
        return this.appointmentsForClient;
    }
    
    public void setAppointmentsForClient(Set<Appointment> appointmentsForClient) {
        this.appointmentsForClient = appointmentsForClient;
    }
    public Set<Appointment> getAppointmentsForAdmin() {
        return this.appointmentsForAdmin;
    }
    
    public void setAppointmentsForAdmin(Set<Appointment> appointmentsForAdmin) {
        this.appointmentsForAdmin = appointmentsForAdmin;
    }
    public Set<Contact> getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set<Contact> contacts) {
        this.contacts = contacts;
    }
    public Set<TimesHasUser> getTimesHasUsers() {
        return this.timesHasUsers;
    }
    
    public void setTimesHasUsers(Set<TimesHasUser> timesHasUsers) {
        this.timesHasUsers = timesHasUsers;
    }
    public Set<Address> getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }
    public Set<Usercountry> getUsercountries() {
        return this.usercountries;
    }
    
    public void setUsercountries(Set<Usercountry> usercountries) {
        this.usercountries = usercountries;
    }




}


