package Hibernate;
// Generated Jan 30, 2019 7:46:47 AM by Hibernate Tools 3.6.0



/**
 * Usercountry generated by hbm2java
 */
public class Usercountry  implements java.io.Serializable {


     private Integer iduserCountry;
     private Country country;
     private User user;

    public Usercountry() {
    }

    public Usercountry(Country country, User user) {
       this.country = country;
       this.user = user;
    }
   
    public Integer getIduserCountry() {
        return this.iduserCountry;
    }
    
    public void setIduserCountry(Integer iduserCountry) {
        this.iduserCountry = iduserCountry;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


